vich_uploader:
    db_driver: orm # Doctrine ORM
    metadata:
        type: attribute

    mappings:
        files_upload:
            uri_prefix: /uploads/file
            upload_destination: '%kernel.project_dir%/public/uploads/file'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
           